[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[nixpacks]
aptPackages = [
  "libgl1-mesa-glx",
  "libglib2.0-0",
  "libsm6",
  "libxrender1",
  "libxext6"
]
